name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'api-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku
      run: heroku login --api-key $HEROKU_API_KEY
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Login to Heroku Container registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: _ 
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: heroku container:push web -a higher-or-lower-reddit-api
      working-directory: api-service
 
    - name: Release image
      run: heroku container:release web -a higher-or-lower-reddit-api
      