name: Deploy Python Script to AWS Lambda

on:
  push:
    branches:
      - main
    #paths:
    #  - 'python-scripts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # CD part
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install and configure AWS CLI
    - name: Install and configure AWS CLI
      run: |
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
      if: success()
      shell: bash

    # Install dependencies into a target directory
    - name: Install Dependencies
      run: |
        cd python-scripts/reddit-posts-updater/
        mkdir -p package
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t package

    # Copy lambda_function.py into the target directory
    - name: Copy Lambda Function
      run: |
        cp python-scripts/reddit-posts-updater/lambda_function.py python-scripts/reddit-posts-updater/package/

    - name: Open Package folder
      run: |
        cd python-scripts/reddit-posts-updater/package
        ls

    # Create a zip archive
    - name: Create Zip Archive
      run: |
        cd python-scripts/reddit-posts-updater/package
        zip -r ../../deploy_package.zip .
      shell: bash

    - name: Unzip Zip Archive
      run: |
        unzip deploy_package.zip -d deploy_package
      shell: bash

    - name: Display unzipped folder
      run: |
        cd deploy_package 
        ls

    # Deploy to Lambda using AWS CLI
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name redditPostsUpdater \
          --zip-file fileb://deploy_package.zip
      shell: bash
