name: Deploy Python Script to AWS Lambda

on:
  push:
    paths:
      - 'python-scripts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # CD part
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install and configure AWS CLI
    - name: Install and configure AWS CLI
      run: |
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
      if: success()
      shell: bash

    # Install dependencies into a target directory
    - name: Install Dependencies
      run: |
        cd python-scripts/reddit-posts-updater/
        mkdir -p lambda_build/package
        pip install -r lambda_build/requirements.txt -t lambda_build/package

    # Copy lambda_function.py into the target directory
    - name: Copy Lambda Function
      run: |
        cp python-scripts/reddit-posts-updater/lambda_function.py python-scripts/reddit-posts-updater/lambda_build/package/

    # Create a zip archive
    - name: Create Zip Archive
      run: |
        cd python-scripts/reddit-posts-updater/lambda_build/
        zip -r deploy_package.zip package/
      shell: bash

    - name: Print contents of the generated ZIP file
      run: unzip -l python-scripts/reddit-posts-updater/lambda_build/deploy_package.zip

    # Deploy to Lambda using AWS CLI
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name redditPostsUpdater \
          --zip-file fileb://python-scripts/reddit-posts-updater/lambda_build/deploy_package.zip
      shell: bash
