name: Deploy Python Script to AWS Lambda

on:
  push:
    paths:
      - 'python-scripts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # CD part
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install and configure AWS CLI
    - name: Install and configure AWS CLI
      run: |
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
      if: success()
      shell: bash

    # Run the package_builder.py script
    - name: Run package_builder.py
      run: |
        cd python-scripts/reddit-posts-updater/
        python package_builder.py
      shell: bash


    # Deploy to Lambda using AWS CLI
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name redditPostsUpdater \
          --zip-file fileb://python-scripts/reddit-posts-updater/lambda_build/deploy_package.zip
      shell: bash
    
      

