name: Deploy Python Script to AWS Lambda

on:
  push:
    paths:
      - 'python-scripts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # CD part
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Run the package_builder.py script
    - name: Run package_builder.py
      run: |
        cd python-scripts/reddit-posts-updater/
        python package_builder.py
        echo "ZIP file created at: ${{ steps.step-id.outputs.zip-file-path }}"
      shell: bash


# Print the source path
    - name: Print Source Path
      run: | 
        echo "Deploying Lambda function with source: ${{ github.workspace }}/python-scripts/reddit-posts-updater/lambda_build/deploy_package.zip"

    # Deploy to Lambda
    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: redditPostsUpdater
        source: ${{ github.workspace }}/python-scripts/reddit-posts-updater/lambda_build/deploy_package.zip

